name: Gitea
version: "1.23.1-v4"
slug: gitea
codenotary: info@fabiogaravini.dev
description: Gitea is a Git hosting, code review, team collaboration, package registry, and CI/CD
url: https://about.gitea.com/
webui: http://[HOST]:[PORT:3000]
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
  - type: data
    read_only: false
  - type: share
    read_only: false
  - type: ssl
backup: cold
backup_exclude:
  - "**/logs"
schema:
  USER_UID: int(1000,)
  USER_GID: int(1000,)
  TZ: str?
options:
  USER_UID: 1000
  USER_GID: 1000
  TZ: Etc/UTC
ports:
  3000/tcp: 3080
  22/tcp: 222
ports_description:
  3000/tcp: Web UI
  22/tcp: SSH
image: fabioogaravini/hassio-{arch}-gitea