---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:9.0.5
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:9.0.5
codenotary:
  signer: info@fabiogaravini.dev
  base_image: notary@home-assistant.io
