name: Gitlab
version: 17.7.1-ce.0-v0
slug: gitlab
codenotary: info@fabiogaravini.dev
description: Gitlab Comunity Edition
url: https://gitlab.com/rluna-gitlab/gitlab-ce
webui: http://[HOST]:[PORT:80]
panel_icon: mdi:gitlab
panel_admin: false
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
    path: /var/opt/gitlab
  - type: data
    read_only: false
    path: /etc/gitlab
  - type: ssl
    read_only: false
backup: cold
backup_exclude:
  - "*/cache"
  - "*/logs"
ports:
  80/tcp: 8088
  443/tcp: null
  22/tcp: 2222
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
  22/tcp: SSH
image: fabioogaravini/hassio-{arch}-gitlab