name: Immich
version: "1.122.3"
slug: immich
description: High performance self-hosted photo and video management solution
url: https://immich.app
webui: http://[HOST]:[PORT:8080]
arch:
  - aarch64
  - amd64
init: false
map:
  - addon_config:rw
  - share:rw
  - media:rw
  - ssl
backup: cold
backup_exclude:
  - "**/machine-learning"
  - "**/logs"
tempfs: true
video: true
devices:
  - /dev/kfd
  - /dev/dri
  - /dev/vchiq
  - /dev/video0
  - /dev/video10
schema:
  PUID: int(0,)
  PGID: int(0,)
  TZ: str?
  MACHINE_LEARNING_WORKER_TIMEOUT: int(0,)
  MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION: str?
  MACHINE_LEARNING_PRELOAD__CLIP: str?
  IMMICH_TRUSTED_PROXIES: str?
  IMMICH_METRICS: bool
options:
  PUID: 0
  PGID: 0
  TZ: Etc/UTC
  MACHINE_LEARNING_WORKER_TIMEOUT: 300
  IMMICH_TRUSTED_PROXIES: 172.30.32.0/23
  IMMICH_METRICS: false
ports:
  8080/tcp: 8080
  5432/tcp: null
  6379/tcp: null
ports_description:
  8080/tcp: Web UI
  5432/tcp: Postgresql DB
  6379/tcp: Redis DB
