name: Immich
version: 1.140.0
slug: immich
codenotary: info@fabiogaravini.dev
description: High performance self-hosted photo and video management solution
url: https://immich.app
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false
  - type: media
    read_only: false
  - type: ssl
backup: cold
backup_exclude:
  - "**/machine-learning"
  - "**/logs"
tmpfs: true
video: true
devices:
  - /dev/kfd
  - /dev/dri
  - /dev/vchiq
  - /dev/video0
  - /dev/video10
schema:
  TZ: str?
  IMMICH_LOG_LEVEL: list(verbose|debug|log|warn|error)
  ssl: bool
  certfile: str?
  keyfile: str?
  DB_STORAGE_TYPE: list(SSD|HDD)
  MACHINE_LEARNING_MODEL_TTL: int(0,)
  MACHINE_LEARNING_WORKER_TIMEOUT: int(0,)
  MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL: str?
  MACHINE_LEARNING_PRELOAD__CLIP__VISUAL: str?
  MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION__RECOGNITION: str?
  MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION__DETECTION: str?
  IMMICH_TRUSTED_PROXIES: str?
  PUID: int(0,)
  PGID: int(0,)
options:
  TZ: Etc/UTC
  IMMICH_LOG_LEVEL: log
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  DB_STORAGE_TYPE: HDD
  MACHINE_LEARNING_MODEL_TTL: 300
  MACHINE_LEARNING_WORKER_TIMEOUT: 300
  IMMICH_TRUSTED_PROXIES: 172.30.32.0/23
  PUID: 0
  PGID: 0
ports:
  8080/tcp: 8080
  5432/tcp: null
  6379/tcp: null
ports_description:
  8080/tcp: Immich
  5432/tcp: Postgresql DB
  6379/tcp: Redis DB
image: fabioogaravini/hassio-immich
