name: Postgres 16
version: "pg16-v0.3.0-v0"
slug: postgres_16
codenotary: info@fabiogaravini.dev
description: Postgres 16 with pgvecto.rs
url: https://www.postgresql.org/about/news/postgresql-16-released-2715
startup: initialize
arch:
  - aarch64
  - amd64
map:
  - type: addon_config
    read_only: false
  - type: media
    read_only: false
  - type: share
    read_only: false
backup: cold
backup_exclude:
  - "*/log"
ports:
  5432/tcp: null
ports_description:
  5432/tcp: Database
options:
  POSTGRES_INITDB_ARGS: "--data-checksum"
  POSTGRES_HOST_AUTH_METHOD: trust
schema:
  POSTGRES_DB: str
  POSTGRES_HOST_AUTH_METHOD: str
  POSTGRES_USER: str
  POSTGRES_PASSWORD: password
  POSTGRES_INITDB_ARGS: str?
environment:
  PGDATA: /config
image: fabioogaravini/hassio-{arch}-postgres-16-pgvectors