name: Cloudflared
version: "2024.12.1"
slug: cloudflared
description: Cloudflare tunneling and Zero Trust service
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: False
    path: /config